### ISSUE TITLE
default Admin password?

### ISSUE THREAD

**Issue by carlosaya** [paybyphone/phpipam_cookbook#1]
Hi, maybe I am missing it, but I don't see the default admin password documented anywhere.  It looks like you are inserting Admin with a hashed password into the users table here:

https://github.com/paybyphone/phpipam_cookbook/blob/master/files/default/ipam_schema_1.2.sql#L344

But I don't see anywhere that you have said what that password is.  Tried all the ones you mentioned in your readme for DB passwords just in case it was the same, but they did not work.

Also, do you take contributions?  Thinking about adding RHEL7 support to yours rather than continuing the cookbook I was already working on.

Thanks!

**Comment by carlosaya** [comment]
disregard, just realized that line is still inserting the default phpipam admin password.  thought you modified it!

**Comment by vancluever** [comment]
Hey @carlosaya, yeah, that's just the schema SQL from the PHPIPAM distribution moved over to the cookbook to make sure it was available at compilation time. Happy you figured it out, and by all means if you have a PR send it in!
